### ISSUE TITLE
error when entering threshold

### ISSUE THREAD

**Issue by BoXoBoXoBoXo** [robertJene/stableDiffusionAutomatic1111tools#2]
I get this error after entering a number for theshold to show loss:

Microsoft VBScript: Type incompatible: 'CDbl'

I don't understand why

`show loss / inspect training -> SHOW LOSS -> ASK FOR THRESHOLD

log folder:
E:\STABLE_DUFFUSION\stable-diffusion-webui\textual_inversion\2023-10-05\test

The default threshold is 0.06 loss, and the output will only show numbers below that.
type 'y' or to continue. Type a number to change the threshold.
***** press enter for the default or enter or a number! nothing else *****
***** the number can be an integer, or have a decimal. examples:
0.08, 1, 0.03 (only enter one value)
enter x to go to ROOT MENU
enter exit to go to quit

: 1

    threshold: 1

E:\STABLE_DUFFUSION\trainingtools\embedding_loss.vbs(65, 9) Erreur d'exécution Microsoft VBScript: Type incompatible: 'CDbl'

Appuyez sur une touche pour continuer...
`

**Comment by robertJene** [comment]
I am replying here even though I helped you elsewhere

Just in case any one sees this

CDbl is a variable type with vbsript in Windows.

If vbscript on your computer can't do it, the issue is with your copy of Windows
